### ISSUE TITLE
EOFError Task Cancellled

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#10]
[yolo_hmap_fullres_100v3-ver-918974.log](https://github.com/user-attachments/files/15794605/yolo_hmap_fullres_100v3-ver-918974.log)
Can you take a look at this error ?
Policy: GazePointNavResNetPolicy

`srun: error: sonny: task 2: Killed
srun: Terminating StepId=918974.0
slurmstepd: error: *** STEP 918974.0 ON sonny CANCELLED AT 2024-06-11T15:37:58 ***
Process ForkServerProcess-29:
Process ForkServerProcess-30:
Traceback (most recent call last):
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/core/vector_env.py", line 294, in _worker_env
    command, data = connection_read_fn()
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-lab/habitat/utils/pickle5_multiprocessing.py", line 68, in recv
    buf = self.recv_bytes()
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError`

**Comment by yusufali98** [comment]
As I have mentioned previously, I think the EOFError is a default error message which is generated whenever one of the processes in the default multiprocessing habitat code runs into an error. You cannot conclude anything from that message as it is very generic.

I would suggest to add additional print statements in the parts of the code that you have modified to better understand what is causing the code to crash

Also please add the experiment config file that you are using for this experiment and associated code branch

**Comment by yusufali98** [comment]
Also, can you please add some specific details of what you have been trying to debug this issue ?

**Comment by AnandSingh-0619** [comment]
Branch: [Anand_dev_YOLO_SAM](https://github.com/AnandSingh-0619/home-robot/tree/anand_dev_heatmap_yolo)
Config file: [YOLOSAM_gaze_rl_skill](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/config/YOLOSAM_gaze_rl_skill.yaml)
Policy: [YoloSAMPointNavResNetPolicy](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/models/YOLOSAMPointNavResNetPolicy.py)

Changes made to debug:
1. Added print statements and logging the current memory usage.
2. Removed the extra key from rollout storage and added a new sensor to store the date from the YOLO-SAM inference.
3. Added print statements at the end of the rollout phase and also the current memory usage.
4. Changing input arguments to the SAM predict function.
5. Handling of the output from the SAM model (as generator object or as list)
6. Used try except to catch exceptions if any occurring in the code

Log for CUDA out of memory:
[yolo_sam_50-ver-918533.log](https://github.com/user-attachments/files/15811533/yolo_sam_50-ver-918533.log)

**Comment by yusufali98** [comment]
The latest log you posted has following traceback:
```
Traceback (most recent call last):
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/run.py", line 151, in <module>
    main()
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/run.py", line 107, in main
    execute_exp(config, "train")
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/trainers/YOLOSAM_trainer.py", line 454, in train
    self._collect_environment_result(buffer_index)
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/trainers/YOLOSAM_trainer.py", line 335, in _collect_environment_result
    self._masks = self._yolo_detector.predict(batch)
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainty/models/YOLOSAMPointNavResNetPolicy.py", line 296, in predict
    sam_outputs = list(self.sam_model.predict(stream=True, source=img, bboxes=combined_boxes, points=None, labels=None, verbose=False))
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/site-packages/ultralytics/engine/predictor.py", line 244, in stream_inference
    im = self.preprocess(im0s)
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/site-packages/ultralytics/models/sam/predict.py", line 102, in preprocess
    im = (im - self.mean) / self.std
```

Do you know why this is happening ?

**Comment by yusufali98** [comment]
It seems like the code ran into CUDA OOM error at [this point](https://github.com/AnandSingh-0619/home-robot/blob/anand_dev_heatmap_yolo/projects/habitat_uncertainty/models/YOLOSAMPointNavResNetPolicy.py#L307-L308)

Is there a reason for creating the `tuple` and using the `next()` oeprator ?

**Comment by AnandSingh-0619** [comment]
1. `sam_outputs = self.sam_model.predict(stream=True, source=img, bboxes=input_boxes, points=None, labels=None, verbose=False)
sam_output = next(sam_outputs)`

2. `sam_outputs = list(self.sam_model.predict(stream=True, source=result.orig_img, bboxes=combined_boxes, points=None, labels=None, verbose=False))
result_masks = sam_outputs[0].masks`
These are different ways to access the sam output.
Using the first one as output has data at first index only


OOM error occurs before the control gets to SAM 
![image](https://github.com/AnandSingh-0619/home-robot/assets/69452312/9b92f6ae-25c3-45d2-a6e6-56b80075c03e)


The log file is too big to share.

**Comment by AnandSingh-0619** [comment]
At the begining of the code execution

`2024-06-25 13:57:30,666 CPU usage: 20.2%`
`2024-06-25 13:57:30,666 RAM usage: 51.8%`
`2024-06-25 13:57:30,666 Disk IO: Read 7302171323904 bytes, Written 1753960457216 bytes`
`2024-06-25 13:57:30,666 Network IO: Sent 1655522230662969 bytes, Received 1655499428570893 bytes`
`2024-06-25 13:57:30,666 Open file descriptors: 2`

Towards the end

`2024-06-25 14:06:30,171 CPU usage: 43.4%`
`2024-06-25 14:06:30,171 RAM usage: 98.8%`
`2024-06-25 14:06:30,171 Disk IO: Read 7304257080832 bytes, Written 1754065107968 bytes`
`2024-06-25 14:06:30,171 Network IO: Sent 1655524248367368 bytes, Received 1655507879648098 bytes`
`2024-06-25 14:06:30,171 Open file descriptors: 0`

RAM usage peaks at 99.9%, which suggests the system is running out of available memory. Even the benchmark code takes more than 50% RAM. I was getting EOF Task Cancelled or Killed as system ran out of memory. 
Most of the cases there was some existing job running on that node which together with my job consumed 100% RAM and my job was killed or cancelled.

**Comment by yusufali98** [comment]
I think we didnt find a solution for the RAM usage peaking right ?

**Comment by AnandSingh-0619** [comment]
Yes, the RAM consumption for training with 32 env is more than 60% for that node. If there is any other task running on that node, the RAM usage would spike to 100% and job would cancel.

**Comment by yusufali98** [comment]
Lets keep this open for future reference
