### ISSUE TITLE
Error running multiple batch jobs of GPU=1

### ISSUE THREAD

**Issue by AnandSingh-0619** [AnandSingh-0619/home-robot#6]
https://github.com/AnandSingh-0619/home-robot/blob/6816b9011ef64a8555107ff42e5a13f35c500e23/job.sh#L1C1-L23C58

I am getting the following error when trying to execute multiple batch jobs on the same homo-robot code.
`Traceback (most recent call last):
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainity/run.py", line 154, in <module>
    main()
  File "/nethome/asingh3064/flash/home-robot/projects/habitat_uncertainity/run.py", line 105, in main
    execute_exp(config, "train")
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/run.py", line 60, in execute_exp
    trainer.train()
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/ppo_trainer.py", line 675, in train
    self._agent.load_state_dict(resume_state)
  File "/coc/pskynet4/asingh3064/home-robot/src/third_party/habitat-lab/habitat-baselines/habitat_baselines/rl/ppo/single_agent_access_mgr.py", line 258, in load_state_dict
    self._lr_scheduler.load_state_dict(state["lr_sched_state"])
  File "/srv/kira-lab/share4/asingh3064/miniforge3/envs/home-robot/lib/python3.9/site-packages/torch/optim/lr_scheduler.py", line 249, in load_state_dict
    lr_lambdas = state_dict.pop('lr_lambdas')
AttributeError: 'tuple' object has no attribute 'pop'`

attached below is the error log file
[home_robo-ver-842723.log](https://github.com/AnandSingh-0619/home-robot/files/14783346/home_robo-ver-842723.log)

**Comment by yusufali98** [comment]
I think this is resolved by setting habitat_baselines.load_resume_state_config=False in the experiment config right ?
If yes, please close comment
